version: '3.8'

services:
  app:
    image: php:8.3-fpm
    container_name: laravel_modules_app
    volumes:
      - .:/var/www/html
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
    driver: bridge
